services:
  radarr-disney:
    container_name: radarr-disney
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7887:7887
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Phoenix
    volumes:
      - ./config:/config
      - /mnt/data/:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - media
networks:
  media:
    external: true
